### ISSUE TITLE
artifacts at bottom of image when using 4:2:0 chroma subsampling

### ISSUE THREAD

**Issue by jonsneyers** [thorfdbg/libjpeg#11]
Especially when using a low quality setting, the bottom few rows of an image are problematic when using chroma subsampling. Here's an example:
![a](https://cloud.githubusercontent.com/assets/15010068/26162604/d71760b2-3b2f-11e7-9f93-8a1976fb3756.jpg)

**Comment by thorfdbg** [comment]
Thank you, this issue was due to a bad upsampling policy at the bottom of the image and should be fixed now.
