### ISSUE TITLE
Decoding - PFM PPM File format interchanging

### ISSUE THREAD

**Issue by Nathees** [thorfdbg/libjpeg#12]
Dear Sir 
	
I have the following doubts in the JPEG XT Decoder
	1) Why are some decoded images saved in PPM Fileformat, when requested to save in PFM      Fileformat?
	2) For a given PFM file, how do I convert the floating point raw pixel value to fixed point value (How to know the bit depth of a pixel from the PFM file)?

Regards,
Natheesan

**Comment by thorfdbg** [comment]
Am 30.06.2017 um 19:24 schrieb Nathees:
> Dear Sir
> 
> I have the following doubts in the JPEG XT Decoder

You mean that you have "questions"?  "doubts" are something different...

> 1) Why are some decoded images saved in PPM Fileformat, when requested
> to save in PFM Fileformat?

The file format depends on the samples in the file. Integer sample
images are saved in ppm, images consisting of floating point samples are
saved in pfm.

> 2) For a given PFM file, how do I convert the floating point raw pixel
> value to fixed point value (How to know the bit depth of a pixel from
> the PFM file)?

A ppm file does not contain floating point samples, so there is nothing
to convert to. PFM, however, does not have a "pixel depth". Each pixel
consists of a 32-bit floating point value.

"raw" does not define a specific format, so it's hard to answer.
Whenever a camera saves something in "raw", it means "in some
proprietary format the vendor made up". How to convert such samples to
absolute or relative luminance, and then represent them as floating
point luminance values is something only the camera vendor can answer
(but usually will not answer).

Greetings,
Thomas

**Comment by Nathees** [comment]
Dear Thomas,

Thanks for the reply.

Regards,
Natheesan
