### ISSUE TITLE
Will project JPEG XT continue?

### ISSUE THREAD

**Issue by Jamaika1** [thorfdbg/libjpeg#18]
Will project JPEG XT continue?
Is there any chance for an update on https://jpeg.org/jpegxt/software.html? 

http://forum.doom9.org/showthread.php?p=1875732#post1875732

**Comment by thorfdbg** [comment]
I'm not quite sure what you expect. JPEG XT is now an international standard, namely ISO/IEC 18477, and what you find here is (one branch) of the reference software. So in that sense, it is complete. Actually, it implements a bit more than JPEG XT as it also supports some modes of JPEG that are not part of XT (hierarchical, lossless, and JPEG LS).

What do you need in particular?

**Comment by Jamaika1** [comment]
Of course. Looking at projects and implementation dates, ISO is all there. The project has ended.
https://www.itscj.ipsj.or.jp/sc29/29w42901.htm#JPEGXT
However, there are publications of codec improvements.
https://www.researchgate.net/publication/332669626_JPEG_XT_Image_Compression_with_Hue_Compensation_for_Two-Layer_HDR_Coding
