### ISSUE TITLE
Question about the Thresholds::InstallDefaults and MAXVAL range in JPEG-LS LSE marker

### ISSUE THREAD

**Issue by vbaderks** [thorfdbg/libjpeg#19]
Hi Thomas Richter,

I have a question about the Thresholds::InstallDefaults(...) method of your library and the text of the JPEG-LS ISO/IEC 14495-1 standard:
Section C.2.4.1.1, Table C.1 of the JPEG-LS standard defines that parameter MAXVAL can be 0 (default) or in the range [1, 2^P>, where P = is the number of bits per image sample.

I would thus assume that MAXVAL can be set to 50 for example when P = 8. Making it possible to create 8 bit images (for compatibility reasons), but use a custom LSE marker to indicate that only values up to 50 are used in the image.

However the method Thresholds::InstallDefaults has as its first parameter bpp, which is internally used to compute bpp and doesn’t allow this flexibility.

What is your opinion about this? Is this range incorrect and is MAXVAL always equal with 2^P -1? 

Thanks, Victor

**Comment by thorfdbg** [comment]
That is correct. Currently, maxval is restricted to 2^P-1. There is currently no API to set MAXVAL to any other value. Frankly, images that would profit from other values are rather rare - but you may try to convince me otherwise if you have a particular use case in mind.
