### ISSUE TITLE
libjpeg FTBFS inside sbuild

### ISSUE THREAD

**Issue by malaterre** [thorfdbg/libjpeg#20]
libjpeg fails to build from source in unstable when building it under
sbuild, because sbuild does not have a writeable $HOME directory:

|    dh_auto_install
|         make -j1 install DESTDIR=/<<BUILDDIR>>/libjpeg-0.0\~git20180720.99764820d250/debian/libjpeg-tools AM_UPDATE_INFO_DIR=no
| make[1]: Entering directory '/<<PKGBUILDDIR>>'
| mkdir: cannot create directory ‘/sbuild-nonexistent’: Permission denied
| make[1]: *** [Makefile:383: install] Error 1
| make[1]: Leaving directory '/<<PKGBUILDDIR>>'
| dh_auto_install: make -j1 install DESTDIR=/<<BUILDDIR>>/libjpeg-0.0\~git20180720.99764820d250/debian/libjpeg-tools AM_UPDATE_INFO_DIR=no returned exit code 2
| make: *** [debian/rules:5: binary] Error 255
| dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2

**Comment by malaterre** [comment]
back ref:

* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939654

**Comment by malaterre** [comment]
Step to reproduce:

```
$ HOME=invalid_path ./configure --prefix=/my/prefix && grep PREFIX automakefile
PREFIX		=	invalid_path/bin/wavelet
```

I looks as if `--prefix` is broken

**Comment by thorfdbg** [comment]
Thank you, this should be fixed. Apparently, this was a misguided attempt to work around an autoconf bug, see here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1225753

I fixed my workaround. Hopefully, autoconf will make this workaround also unnecessary.
