### ISSUE TITLE
libjpeg fails to cross build from source

### ISSUE THREAD

**Issue by malaterre** [thorfdbg/libjpeg#22]
> libjpeg fails to cross build from source, because it configures for the
> build architecture. Unconventionally, ./configure is invoked by the
> Makefile during dh_auto_build. This happens, because the Makefile also
> performs autoconf and thus debhelper uses the makefile buildsystem due
> to the absence of configure. Enabling autoreconf makes debhelper select
> the autoconf buildsystem and run ./configure with --host. However,
> configuration fails due to frequent use of AC_TRY_RUN. The attached
> patch adds autoreconf and fixes a lot of AC_TRY_RUN, but not all. It is
> an incremental improvement and does not make libjpeg cross buildable.
> Please consider applying it anyway and close this bug when doing so.

ref:

* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947139

Patch is at:

* https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=947139;filename=libjpeg_0.0~git20190821.87636f3b26b4-1.1.debdiff;msg=5

**Comment by thorfdbg** [comment]
I made some changes to configure.in to address the issues, though the problem with worst-case struct-alignment remains. I would not know how to address this without AC_TRY_RUN. Help appreciated.
