### ISSUE TITLE
Assertion failure at coding/blockrow.hpp:93

### ISSUE THREAD

**Issue by rainoftime** [thorfdbg/libjpeg#24]
Hi, for the following input,
[93.txt](https://github.com/thorfdbg/libjpeg/files/4768898/93.txt)

jpeg throws an assertion failure
~~~~
jpeg: ../coding/blockrow.hpp:93: BlockRow<T>::Block* BlockRow<T>::BlockAt(ULONG) const [with T = int; ULONG = unsigned int]: Assertion `pos < m_ulWidth' failed.
Aborted
~~~~

OS: Ubuntu 16.04
Commit: cf4cc9cfd2

**Comment by thorfdbg** [comment]
Thank you for the report, this will be fixed in the next release.
