### ISSUE TITLE
About Decoding 

### ISSUE THREAD

**Issue by LingyunWang** [thorfdbg/libjpeg#3]
Dr. Richter
It seems that the libjpeg provide only encoding function,but no decoding reference. Is that true?
If so, where can I find some implementation? I am developing an application of JPEG-XT. Be grateful for your notify.

**Comment by thorfdbg** [comment]
Am 16.05.2016 um 09:49 schrieb LingyunWang:
> Dr. Richter
> It seems that the libjpeg provide only encoding function,but no decoding
> reference. Is that true?

No.

> If so, where can I find some implementation? 

It's right in front of you. To decode, just pass the jpeg image into the
command line tool as follows:

jpeg input.jpg out.pfm

or

jpeg input.jpg out.ppm

Greetings,
	Thomas

**Comment by LingyunWang** [comment]
Thanks a lot for your point!
After reading source coke,I find the entry function of decoding process is 

> extern void Reconstruct(const char *infile,const char *outfile,int colortrafo,const char *alpha);

**Comment by LingyunWang** [comment]
Hello, Dr.Richer
1.In HDR Encoding,  LDR->RGBToTCbCr->DCT->QNT->Inverse QNT->IDCT->YCbCrToRGB->Inverse TMO.
What confuse me, Before caculating residual, where is Inverse TMO?
blockBitmaprequester.cpp Line 844
` ctrafo->RGB2Residual(r,m_ppTempIBM,m_ppDTemp,m_ppRTemp);	`

2.LDR is 8bits, Residual is 16 bits, Whit is difference in huffman encoding?

Expect for your reply at your convience

**Comment by thorfdbg** [comment]
Am 30.05.2016 um 14:36 schrieb LingyunWang:
> Hello, Dr.Richer
> 1.In HDR Encoding, LDR->RGBToTCbCr->DCT->QNT->Inverse
> QNT->IDCT->YCbCrToRGB->Inverse TMO.
> What confuse me, Before caculating residual, where is Inverse TMO?

The inverse TMO is applied in YCbCrTrafo::RGB2Residual as
m_plDecodingLUT[i]. It is called there the "L-Transformation" which is
its historical name.

> 2.LDR is 8bits, Residual is 16 bits, Whit is difference in huffman encoding?

The LDR in the DCT domain is 12 bits wide, not 8 bits. The size of the
DCT coefficients in the residual domain is between 12 to 16 bits,
depending on whether residual refinement is turned on or not, at least
in part 7, profile C. There are no changes for the Huffman coding
because the (up to) 16 bits are not coded in a single round, hence, no
changes need to be made.

The specifications for refinement coding are specified in ISO/IEC
18477-6 and explained there, but briefly:

The first 12-bits (standard resolution) are encoded following the
regular Huffman coding process,

The additional "residual refinement" bits are encoded with the
"Successive approximation" scan of JPEG, which is specified in ISO/IEC
10918-1, there part of "progressive JPEG".

Within this code, standard (sequential) coding is
codestream/sequentialscan.cpp, the refinement scans - including handling
of subsequent refinement of successive approximation coding of
progressive JPEG - in codestream/refinementscan.cpp.

Greetings,
Thomas

**Comment by LingyunWang** [comment]
Hello,Dr Richer
Thanks a lot.
1 In the decoding,I know part 4 map LDR to HDR, following part 4a, called C-Transformation.
In code ycbcrtrafo.cpp void YCbCrTrafo<external,count,oc,trafo,rtrafo>::YCbCr2RGB
`rx = FIX_TO_INT(QUAD(rv) * m_lC[0] + QUAD(gv) * m_lC[1] + QUAD(bv) * m_lC[2]);`
What's the function of this transformation, and what is the meaning of FIX_BITS and COLOR_BITS?
These macro FIX_TO_INT, FIX_TO_COLOR confuse me a lot.

2 In part B7 and part B8d, what is the functions of the two NLT transformation?

Greetings,
Lingyun

**Comment by thorfdbg** [comment]
Am 04.06.2016 um 17:11 schrieb LingyunWang:
> Hello,Dr Richer
> Thanks a lot.
> 1 In the decoding,I know part 4 map LDR to HDR, following part 4a,
> called C-Transformation.
> In code ycbcrtrafo.cpp void YCbCrTrafo::YCbCr2RGB
> |rx = FIX_TO_INT(QUAD(rv) * m_lC[0] + QUAD(gv) * m_lC[1] + QUAD(bv) *
> m_lC[2]);|
> What's the function of this transformation, and what is the meaning of
> FIX_BITS and COLOR_BITS?

The purpose of this transformation is to convert the color space of the
LDR image (typically BT.709) to the colorspace of the HDR space
(probably BT.2020). Or at least, using the C-transformation is one
possible option how to encode images in a larger color space. Another
option is just to use residual coding and leave the C transformation the
identity (which is the default).

Profile C mirrors the implementation specifications in ISO/IEC 18477-8
and hence implements everything in fixpoint precision. FIX_BITS and
COLOR_BITS specify the number of fractional bits in the fixpoint
representation, both of the reconstructed coefficients and of the
coefficients of the linear transformation.

> 2 In part B7 and part B8d, what is the functions of the two NLT
> transformation?

The residual NLT point transformation (B7) typically scales the residual
to the range that is representable by the residual decoder (8 bit, or 12
bit with the 12-bit process or the 8-bit process with 4 refinement
bits). B8d (secondary residual transformation) can in principle do the
same. It is mostly here to mirror a similar box in part 8 where it is
required to reduce the bitdepth for the RCT.

By default, these two boxes are absent, i.e. replaced by their default
function (which is scaling).

Greetings,
	Thomas

**Comment by LingyunWang** [comment]
Hello, Dr Richer
> The residual NLT point transformation (B7) typically scales the residual
to the range that is representable by the residual decoder (8 bit, or 12
bit with the 12-bit process or the 8-bit process with 4 refinement
bits). B8d (secondary residual transformation) can in principle do the
same. 
> 

1 You mean B7 and B8d scales the residual's range from 8bit(or 12bit) to 16 bit?
If B7 already scalse the range from 8 bit(or 12 bit) to 16 bit, why we need the 2nd Residual NLT?



>The LDR in the DCT domain is 12 bits wide, not 8 bits. The size of the
DCT coefficients in the residual domain is between 12 to 16 bits
> 

2 Is the leagcy code stream of LDR is 8 bit,and the refinement code is 4 bit ?
In residual，Is leagcy stream also 8 bit，and the refinemenet is between 4 bit to 8 bit?

**Comment by thorfdbg** [comment]
Am 06.06.2016 um 04:51 schrieb LingyunWang:
>
> Hello, Dr Richer
>
>     The residual NLT point transformation (B7) typically scales the
>     residual
>     to the range that is representable by the residual decoder (8 bit,
>     or 12
>     bit with the 12-bit process or the 8-bit process with 4 refinement
>     bits). B8d (secondary residual transformation) can in principle do the
>     same.
>
> 1 You mean B7 and B8d scales the residual's range from 8bit(or 12bit)
> to 16 bit?
> If B7 already scalse the range from 8 bit(or 12 bit) to 16 bit, why we
> need the 2nd Residual NLT?
>

I would really suggest getting the standard from ISO and check there.
The residual NLT (B7) has an input scale of P+Rr bits (P=precision
of the residual, Rr=number of residual refinement bits) and an output
scale of 8+Rb bits, where Rb are the extra bits in the spatial domain. For
part 7, Rb=8, hence: B7 scales from 8 or 12 bits to 16 bits. In the
absense of a box, this indicates a linear scaling. (See Annex C of
ISO/IEC 18477-6
for this).

Now, the intermediate residual NLT (block B8d) has an input scale of
Rb+8=16 and an output scale of Rb+8=16, hence does nothing in the absense
of any explicit specification. The reason for this is as follows: As you
see, the signal coming from the residual is added to the base image. Given
that the output range is 16 bit and the NLT-transformed base image is
also 16 bit, the residual must be difference image. Hence, it has a
dynamic range
of -2^16 to +2^16, and hence - in worst case - overshoots the capacity
of the residual and the color transformation there.
*If* this happens, you need to scale the residual down by one bit. This
*can* be done by the intermediate residual NLT.



>     The LDR in the DCT domain is 12 bits wide, not 8 bits. The size of the
>     DCT coefficients in the residual domain is between 12 to 16 bits
>
> 2 Is the leagcy code stream of LDR is 8 bit,and the refinement code is
> 4 bit ?
>

No, I'm talking about the amplitude/dynamic range of the DCT
coefficients. If I enter the DCT with 8 bits, the result is a 12 bit
signal, i.e.
the DCT coefficients of an 8-bit image may have an amplitude that covers
a dynamic range of up to 12 bits. Hence, you need a 12-bit Huffman
alphabet to encode an 8-bit image. This is precisely what the old JPEG
does. Of course, if you have an additional 4 bit refinement scan, you
can enter the DCT with 12 bits, and you get a 16-bit signal. This 16-bit
signal is then encoded either with the 12-bit Huffman process (legacy
JPEG) plus 4 refinement bits, or by the (little known) 16-bit Huffman
process also available in JPEG.


> In residual，Is leagcy stream also 8 bit，and the refinemenet is
> between 4 bit to 8 bit?
>
Refinement bits can be added to the legacy domain or to the residual
domain - either way. For profile C, I would *typically* suggest to
only use refinement coding in the residual domain *or* use a 12-bit
process in the residual domain. This will typically offer good quality.

You *can* get away with an 8-bit residual only, but quality will not be
as good.

Greetings,
    Thomas
