### ISSUE TITLE
Lossless Jpeg

### ISSUE THREAD

**Issue by egorsh0** [thorfdbg/libjpeg#4]
Hello, Dr. Richter
I have two images Lossless Jpeg: 8 and 12 bits. I am doing 8-bit decoding in any other format, and all is well. The question is, how do I make the decoding of 12 bit? What specify flags?

**Comment by thorfdbg** [comment]
Am 06.07.2016 um 17:56 schrieb egorsh:
> Hello, Dr. Richter
> I have two images Lossless Jpeg: 8 and 12 bits. I am doing 8-bit
> decoding in any other format, and all is well. The question is, how do I
> make the decoding of 12 bit? What specify flags?

None. If the input is 12 bits, the output will also be 12 bits, no need
to tell the decoder anything.

**Comment by egorsh0** [comment]
Tell me, how to use your library? I have a project where I want to just convert the image. As I understand it, you need to install the library from source files. Do not you have an example of use for the conversion?

**Comment by thorfdbg** [comment]
Am 12.07.2016 um 12:41 schrieb egorsh:
> Tell me, how to use your library? 

Example compression code that is also good for JPEG-LS, lossless JPEG
and lossless JPEG XT is in cmd/encodec.cpp. Example decoder code is in
cmd/reconstruct.cpp. While part of the distribution, these files are
logically not part of the core library.

> I have a project where I want to just
> convert the image. As I understand it, you need to install the library
> from source files. 

You would probably need to invest some work to create a link library.
The library entry points are interface/jpeg.hpp.

> Do not you have an example of use for the conversion?

See the above files.

Greetings,
	Thomas

**Comment by oumaima78** [comment]
hello ,could you help me please to solve this problem :when I try to compress a HDR image using this command : $ jpeg -r -q 20 -Q 5 -h -profile c -rR 4 chairs.pfm chairs20_5.jpg
It tolds me that" no command jpeg is found"
 what should I do?
I am using ubuntu 16.04

**Comment by thorfdbg** [comment]
On 30.05.2017 15:21, oumaima78 wrote:
> hello ,could you help me please to solve this problem :when I try to
> compress a HDR image using this command : $ jpeg -r -q 20 -Q 5 -h
> -profile c -rR 4 chairs.pfm chairs20_5.jpg
> It tolds me that" no command jpeg is found"
> what should I do?
> I am using ubuntu 16.04

I guess you first need need to compile the jpeg command. Did this
succeed? Then, depending on your shell configuration, you may have to
run it explicitly from the current directory, such as:

./jpeg -r -q 20 -Q 5 -h -profile c -rR 4 chairs.pfm chairs20_5.jpg

Note the "./" upfront.

HTHH,
	Thomas

**Comment by oumaima78** [comment]
I have tried this command but it doesn't work


________________________________
De : Thomas Richter <notifications@github.com>
Envoyé : mercredi 31 mai 2017 09:43:56
À : thorfdbg/libjpeg
Cc : oumaima78; Comment
Objet : Re: [thorfdbg/libjpeg] Lossless Jpeg (#4)

On 30.05.2017 15:21, oumaima78 wrote:
> hello ,could you help me please to solve this problem :when I try to
> compress a HDR image using this command : $ jpeg -r -q 20 -Q 5 -h
> -profile c -rR 4 chairs.pfm chairs20_5.jpg
> It tolds me that" no command jpeg is found"
> what should I do?
> I am using ubuntu 16.04

I guess you first need need to compile the jpeg command. Did this
succeed? Then, depending on your shell configuration, you may have to
run it explicitly from the current directory, such as:

./jpeg -r -q 20 -Q 5 -h -profile c -rR 4 chairs.pfm chairs20_5.jpg

Note the "./" upfront.

HTHH,
Thomas

**Comment by oumaima78** [comment]
________________________________
De : oumaima yahyaoui <oumaimayahyaoui@outlook.com>
Envoyé : jeudi 1 juin 2017 17:15:20
À : thorfdbg/libjpeg
Objet : RE: [thorfdbg/libjpeg] Lossless Jpeg (#4)


I have tried this command but it doesn't work


________________________________
De : Thomas Richter <notifications@github.com>
Envoyé : mercredi 31 mai 2017 09:43:56
À : thorfdbg/libjpeg
Cc : oumaima78; Comment
Objet : Re: [thorfdbg/libjpeg] Lossless Jpeg (#4)

On 30.05.2017 15:21, oumaima78 wrote:
> hello ,could you help me please to solve this problem :when I try to
> compress a HDR image using this command : $ jpeg -r -q 20 -Q 5 -h
> -profile c -rR 4 chairs.pfm chairs20_5.jpg
> It tolds me that" no command jpeg is found"
> what should I do?
> I am using ubuntu 16.04

I guess you first need need to compile the jpeg command. Did this
succeed? Then, depending on your shell configuration, you may have to
run it explicitly from the current directory, such as:

./jpeg -r -q 20 -Q 5 -h -profile c -rR 4 chairs.pfm chairs20_5.jpg

Note the "./" upfront.

HTHH,
Thomas

**Comment by SimonBiggs** [comment]
The following may be helpful to you:

https://stackoverflow.com/a/12653208/3912576
