### ISSUE TITLE
Problem with create jpeg 12bit

### ISSUE THREAD

**Issue by Jamaika1** [thorfdbg/libjpeg#46]
jpegXT.exe -q 90 -a -qt 3 -c -r12 -g 1.0 -s 1x1,1x1,1x1 image_21447.ppm image_21447_12xt.jpg
```
Image
Format                                   : JPEG
Width                                    : 1 563 pixels
Height                                   : 1 558 pixels
Color space                              : YUV
Chroma subsampling                       : 4:4:4
Bit depth                                : 8 bits
Compression mode                         : Lossy
Stream size                              : 8.75 MiB (100%)
```
8bit -> (12bit) in conteiner JPEG 8bit?

```
Image
Format                                   : JPEG
Width                                    : 1 563 pixels
Height                                   : 1 558 pixels
Color space                              : RGB
Bit depth                                : 12 bits
Compression mode                         : Lossy
Stream size                              : 8.29 MiB (100%)
```
JPEGXT in program _ImageConverter Plus_

**Comment by thorfdbg** [comment]
Yes. The former is JPEG XT, with an 8 bit base image and a 12 bit residual, which is backwards compatible to all JPEG viewers. The latter seems to be a native 12-bit image which is not decodeable by many JPEG implementations. It is decodable by this implementation, of course. The former is conforming to 10918-1 (JPEG) and 18477-7 (JPEG XT part 7), the latter is conforming to 10918-1, though many implementations do not implement this standard fully, and thus would not be able to decode the codestream.
