### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ameuret** [thorfdbg/libjpeg#51]
~~comming~~ -> coming
![image](https://user-images.githubusercontent.com/28158/113407948-5b199b80-93e9-11eb-8f7c-20add32e269f.png)

**Comment by malaterre** [comment]
see 5ba26b8c8eb4d74452ed7bc312f7b0edcb79c1d1

**Comment by thorfdbg** [comment]
Thank you, silly me. Fixed!
