### ISSUE TITLE
Problem about compress HDR images

### ISSUE THREAD

**Issue by Yliu724** [thorfdbg/libjpeg#54]
I first use the following code:

jpeg -r -q 40 -Q 50 -h -profile c -rR 4 input.pfm outfile.jpg

And here I get the corresponding compressed and tone-mapped LDR image. 

I would like to know how to get the corresponding HDR images (in radiance RGBE (.hdr) or OpenEXR (.exr) format)? I try to change the format of the output file, 

jpeg -r -q 40 -Q 50 -h -profile c -rR 4 input.pfm outfile.pfm 

and convert the output.pfm to hdr image, is it right? Thanks a lot for your help!

**Comment by thorfdbg** [comment]
You get the compressed image back by:

jpeg outfile.jpg output.pfm

This runs the expander, the output is a pfm file. Note that libjpeg is not a format converter, it only reads and writes pfm files. However, to convert this to radiance hdr, you can use "difftest_ng" on my github page (same page):

difftest_ng --convert output.hdr input.pfm -

Don't forget the terminating dash, indicating that there is no second image to compare to.
