### ISSUE TITLE
Allow creation of default Baseline JPEG image: JPGFLAG_BASELINE

### ISSUE THREAD

**Issue by malaterre** [thorfdbg/libjpeg#59]
`jpeg` command line tool does not allow creation of default baseline JPEG, it always default to sequential extended:

* https://github.com/thorfdbg/libjpeg/blob/master/cmd/encodec.cpp#L345

`int frametype = JPGFLAG_SEQUENTIAL;
`

There is no way then to reset back `frametype` to `JPGFLAG_BASELINE`.

Typical setup (create an 8x8 RGB black image):

```
$ convert -depth 8 -size 8x8 xc:black black.ppm
$ jpeg -h -s 1x1,2x2,2x2 -q 100 black.ppm black_jpeg.jpg
```
compare to the ijg/turbo-jpeg:

`$ cjpeg -optimize -quality 100 -outfile black_cjpeg.jpg black.ppm`

libjpeg it creating:

* `SOF1 `Huffman Extended Sequential DCT

while ijg/turbo-jpeg creates:

* `SOF0 `Huffman Baseline DCT

(as a side note it would also be nice to be able to remove the `APPB `marker completely).

**Comment by thorfdbg** [comment]
Added a "-bl" option to enforce encoding in the baseline mode. Please test and re-open if this does not work as expected.
