### ISSUE TITLE
Usage in external project

### ISSUE THREAD

**Issue by isnullxbh** [thorfdbg/libjpeg#6]
Hellow ! It is possible to use libjpeg library in external project ? If it is possible, what files i must append to my project ? (headers)

**Comment by thorfdbg** [comment]
Sorry for the late reply. Yes, it is possible to use the library in external projects. The files you need to include in your project are in the "interface" directory, the call-in interface is in "interface/jpeg.hpp". Everything that is under "cmd" is just a demo front-end.

**Comment by isnullxbh** [comment]
Thank you !
