### ISSUE TITLE
qtable?

### ISSUE THREAD

**Issue by zvezdochiot** [thorfdbg/libjpeg#61]
Maybe add?:

`-qtables FILE`  Use quantization tables given in FILE.

**Comment by thorfdbg** [comment]
Thanks for the suggestion. I added corresponding options in the 1.62 release. The command line options are derived from the quantization table specifications, with an "f" at the end. Thus, -qtf, -rqtf, -aqtf, -arqtf to specify file names for the legacy quantization tables, for the residual process, for the alpha tables, for the alpha residual tables.

Please test and provide feedback, re-open if it doesn't work.

**Comment by zvezdochiot** [comment]
Hi @thorfdbg .

Where are these releases?

**Comment by thorfdbg** [comment]
In the trunk, just make a "git pull".

**Comment by zvezdochiot** [comment]
@thorfdbg say:
>In the trunk, just make a "git pull".

Its no release! Release is https://github.com/libjpeg-turbo/libjpeg-turbo/releases

**Comment by thorfdbg** [comment]
It's a release when I say it's a release. This is *not* libjpegturbo, and not related to libjpeg-turbo. This repository contains the part of the JPEG reference software that comes out of ISO SC29/WG1. Libjpegturbo is *also* a reference software, but a different source, developed by a different individual.

**Comment by thorfdbg** [comment]
The version is in "README.history" and "README". It's 1.62 at present.

**Comment by ValZapod** [comment]
[jpeg.zip](https://github.com/thorfdbg/libjpeg/files/8040938/jpeg.zip)
64 bit compiled with VS 2022.
