### ISSUE TITLE
Decompression failure with lossless huffman

### ISSUE THREAD

**Issue by scaramallion** [thorfdbg/libjpeg#63]
I seem to be unable to correctly decode [this JPEG file](https://drive.google.com/file/d/1doLyGXNqF-6BKrxuctqthw8QyDB8IUAw/view?usp=sharing) which appears to be lossless huffman. Compiling the current `master` and running `jpeg A_1465_1.RIGHT_MLO.LJPEG out.ppm` gives:
![mlo](https://user-images.githubusercontent.com/10226372/151136857-db271f8b-155d-4e5e-84fb-58cc8f5e92ae.png)

Rather than what it should (apparently) look like, although probably without the red markup:
![A_1465_1 RIGHT_MLO LJPEG 1_highpass](https://user-images.githubusercontent.com/10226372/151136899-9e468b63-5cfd-4f36-ab30-c082aa4a7701.gif)

The proportions are obviously different, but while changing X and Y around in the codestream gives a somewhat recognisable image, it still looks really bad.

Any assistance is appreciated

**Comment by thorfdbg** [comment]
Am 26.01.22 um 10:26 schrieb scaramallion:
> I seem to be unable to correctly decode this JPEG file

Pardon me, but what do you expect? As far as I can tell, there are
multiple things wrong about this codestream. You have already observed
that width and height are confused, so image dimensions are wrong.
Second, it seems it to use incorrect prediction. While it signals a
diagonal predictor, it seems to use no prediction at all. You can try
that by patching up codestream/predictor.hpp, and replace there the
diagonal predictor with no prediction at all. Note, however, that this
would be in violation to the standard.

Greetigs,
	Thomas

**Comment by scaramallion** [comment]
OK, thanks, I wasn't sure if it was just a dodgy JPEG or something else.

Thanks!
