### ISSUE TITLE
Decode failure due to unknown App14 version

### ISSUE THREAD

**Issue by scaramallion** [thorfdbg/libjpeg#92]
Hi, I've got an RGB JPEG image (of unknown provenance) with an APP14 Adobe marker, version 101 but correct length. Attempting to decode gives a -1038 error with "A misplaced marker segment was found - Adobe marker version unrecognized". Is it possible to: 

* Add the ability to decode v101 APP14 markers, and/or
* If the APP14 marker version is unknown, skip it and continue with decoding?

According to: https://pdfa.org/norm-refs/5116.DCT_Filter.pdf the colour transform flag is in the same position as for v100.

![image](https://github.com/thorfdbg/libjpeg/assets/10226372/f52fe351-d0c0-4030-a46e-33b15864d16e)

Start of codestream with the APP14 and including the start marker of DQT is:
```
FF D8 FF EE 00 0E 41 64 6F 62 65 00 65 00 00 00 00 00 FF DB ...
```

Thanks, I really appreciate all the work you've done.

**Comment by thorfdbg** [comment]
Decoder support for version 101 of the Adobe marker was added in 1.68. Fixed and closed.

**Comment by scaramallion** [comment]
Thanks!
